### ISSUE TITLE
提供的longmarch.sql默认的用户名和密码登录不上去

### ISSUE THREAD

**Issue by HaoZhang95** [yuyueqty/longmarch#2]
该数据库文件中sys_user表中只有一个10000001的用户, 该用户的密码为123456, 但是登录不上去, 报错如下:

javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
	at java.base/com.sun.crypto.provider.CipherCore.prepareInputBuffer(CipherCore.java:1005) ~[na:na]
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:848) ~[na:na]
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446) ~[na:na]
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202) ~[na:na]
	at top.longmarch.lmcore.conf.AesService.aesDecryptByBytes(AesService.java:57) ~[classes/:na]
	at top.longmarch.lmcore.conf.AesService.aesDecrypt(AesService.java:69) ~[classes/:na]
	at top.longmarch.lmcore.shiro.filter.ShiroCredentialsMatcher.aesDecrypt(ShiroCredentialsMatcher.java:82) ~[classes/:na]
	at top.longmarch.lmcore.shiro.filter.ShiroCredentialsMatcher.doCredentialsMatch(ShiroCredentialsMatcher.java:51) ~[classes/:na]
	at org.apache.shiro.realm.AuthenticatingRealm.assertCredentialsMatch(AuthenticatingRealm.java:597) ~[shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:578) ~[shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180) ~[shiro-core-1.3.2.jar:1.3.2]

**Comment by HaoZhang95** [comment]
望修复,排查下,已尝试,但未排查出原因
